fast_livo:
  ros__parameters:
    analysis:
      plot_time: -10.0
      frame_cnt: 6
      publish_sparse_depth_map: false
      # Generate the images showing the patches projected in the image frame
      generate_projection_images: true
      reconstructed_view_levels: 
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      lidar_projection_en: false
      depth_discontinuity_overlay_on_depth_map: false
      publish_vio_optimization_points: false
      publish_vio_point_candidates: true
      publish_camera_intrinsics: false
      draw_camera_axes_on_rgb: true
      camera_intrinsics_every_n_vio_iters: 30
      publish_converged_points: false
    common:
      img_topic: "/flyastick/camera/raw"
      lid_topic: "/flyastick/lidar/mock"
      imu_topic: "/flyastick/imu"
      img_en: 1
      lidar_en: 1
      ros_driver_bug_fix: false
      colorize_map_en: false
    camera_id: 0 # Overriden in the Offline app
    extrin_calib: # In the IMU frame
      # Convention used:
      # 
      # P_imu = R * P_frame + T
      # With R being the rotation from FRAME to IMU
      # And T being the position of FRAME origin expressed in IMU frame
      # 
      # Except parameters defined initially, new parameters are written as such:
      #
      # P_target = R_target_source * P_source + T_target_source

      # P_imu = R_imu_lidar * P_lidar + T_imu_lidar

      # Real LiDAR
      extrinsic_T: # Lidar frame origin in IMU frame
      - 0.08100
      - 0.0
      - 0.08346
      extrinsic_R: # Lidar to IMU rotation as quaternion (qx, qy, qz, qw)
      -  0.0
      - -0.0436194
      -  0.0
      -  0.9990482

      # Direct Lidar to Camera transformation (row major)
      # P_camera = R_camera_lidar * P_lidar + T_camera_lidar
      R_camera_lidar: # Direct Lidar -> Camera (row major) (in which frame ?)
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      T_camera_lidar: # Lidar position in Camera frame
      - 0.0
      - 0.0
      - 0.0
    intermediate_camera_extrinsics:
      use_intermediate_extrinsic: true
      # Intermediate transformation is used to transform a point
      # in Camera frame into IMU frame passing by VIO frame:
      # P_vio = R_vio_camera * P_camera + T_vio_camera
      # P_imu = R_imu_vio * P_vio + T_imu_vio
      #
      # By composition:
      # P_imu = R_imu_vio * (R_vio_camera * P_camera + T_vio_camera) + T_imu_vio
      # so
      # R_imu_camera = R_imu_vio * R_vio_camera
      # T_imu_camera = R_imu_vio * T_vio_camera + T_imu_vio
      T_body_vio: # VIO frame origin in IMU frame
      -  0.27111
      - -0.03695
      - -0.01281
      R_body_vio: # VIO to IMU rotation as quaternion (qx, qy, qz, qw)
      -  0.0014743778504144119
      - -0.03566559290068305
      - -0.0021400304501420606
      -  0.9993604014381746
      cameras:
        camera_0:
          T_camera_vio: # Camera frame origin in VIO frame
          -  0.0074364953
          -  0.0054983795
          - -0.019824242
          R_camera_vio: # Camera to VIO rotation as quaternion (qx, qy, qz, qw)
          -  0.6959948
          - -0.7000796
          -  0.11319699
          -  0.11254422
        camera_1:
          T_camera_vio: # Camera frame origin in VIO frame
          -  0.015250832
          -  0.005461842
          -  0.0075625316
          R_camera_vio: # Camera to VIO rotation as quaternion (qx, qy, qz, qw)
          - -0.25782177
          -  0.25593948
          - -0.6613388
          - -0.65624225
        camera_2:
          T_camera_vio: # Camera frame origin in VIO frame
          -  0.019338505
          -  0.0064584436
          - -0.008463549
          R_camera_vio: # Camera to VIO rotation as quaternion (qx, qy, qz, qw)
          -  0.5480533
          - -0.54892504
          -  0.4477863
          -  0.44475424
    time_offset:
      imu_time_offset: 0.0
      img_time_offset: 0.0
      exposure_time_init: 0.0
    preprocess:
      video_downsampler: 3 # Downsampling from 30Hz to 10Hz for images
      point_filter_num: 1
      filter_size_surf: 0.1
      lidar_type: 3
      scan_line: 32
      blind: 0.3
      feature_extract_enabled: false
    vio:
      max_iterations:  8
      outlier_threshold: 500.0
      new_feature_min_translation: 0.5 # Min camera translation (m) before adding a new observation to an existing visual point
      new_feature_min_rotation: 0.3 # Min camera rotation (rad) before adding a new observation to an existing visual point
      new_feature_min_pixel_dist: 40.0 # Min pixel displacement before adding a new observation to an existing visual point
      img_point_cov: 1000.0
      patch_size: 8
      patch_pyrimid_level: 4
      normal_en: true
      orientation_check_en: false
      max_view_angle: 85.0 # Max view angle in degrees for the orientation check
      ncc_en: false
      ncc_outlier_threshold: 0.95
      raycast_en: true
      raycast_d_min: 0.1
      raycast_d_max: 20.0
      raycast_step: 0.2
      depth_discontinuity_threshold: 0.5
      inverse_composition_en: false
      exposure_estimate_en: true
      inv_expo_cov: 0.1
      grid_size: 27
      min_shitomasi_score: 5.0
    imu:
      imu_en: true
      imu_int_frame: 200 # 200 <=> 1s | 1000 <=> 5s | 2000 <=> 10s

      # Taken from LVIO
      # sigma_gyro: 0.01
      # sigma_accel: 0.1
      # sigma_bias_gyro: 0.0001
      # sigma_bias_accel: 0.1
      # 
      # Here we configure the covariance (sigma squared)
      # => sigma_gyro^2 = 0.01^2 = 0.0001
      # => sigma_accel^2 = 0.1^2 = 0.01
      # => sigma_bias_gyro^2 = 0.0001^2 = 0.00000001
      # => sigma_bias_accel^2 = 0.1^2 = 0.01
      acc_cov: 0.5
      gyr_cov: 0.01
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
    lio:
      max_iterations: 10

      # According to Ouster REV7
      # 0.3–1 m: σᵣ = 0.02 m
      # 1–10 m: σᵣ = 0.01 m
      # 10–15 m: σᵣ = 0.015 m
      # >15 m: σᵣ = 0.05 m
      dept_err: 0.02 # Standard deviation (1 sigma)

      # According to Ouster REV7 documentation : "Beam Divergence 0.35° (FWHM)"
      # FWHM (Width of the gaussian at half of the maximum height) corresponds to
      # roughly 76% of the distribution, or 2.355·sigma
      # Therefore : sigma = FWHM/2.335 ~= 0.15°
      beam_err: 0.05 # Standard deviation (1 sigma)
      
      min_eigen_value: 0.0001
      voxel_size: 0.1
      max_layer: 2
      max_points_num: 50
      layer_init_num:
      - 5
      - 5
      - 5
      - 5
      - 5
    local_map:
      map_sliding_en: true
      half_map_size: 100
      sliding_thresh: 8.0
    uav:
      imu_rate_odom: true # Enable IMU propagation
      gravity_align_en: true
    publish:
      dense_map_en: false
      pub_effect_point_en: false
      pub_plane_en: false
      pub_rgb_img: true
      publish_visible_voxels: false
      pub_scan_num: 1
      blind_rgb_points: 0.00
    evo:
      seq_name: "exp11_lower_gallery"
      pose_output_en: true
    pcd_save:
      pcd_save_en: false
      colmap_output_en: false
      save_dense_map: false
      filter_size_pcd: 0.2
      interval: 100
